---
- name: "Creating all the necessary hosts for OpenShift. Check the file openshift.config"
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
     - openshift.config
  roles:
     - { role: "{{ cloud_provider }}_ocp_delete_hosts" }
     - { role: "{{ cloud_provider }}_ocp_compute" }
