#!/usr/bin/env ansible-playbook
---
- name: "STEP #2: Creating all the necessary hosts for OpenShift"
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
     - openshift.config
  pre_tasks:
     - fail: msg="admin_username is not defined or is empty"
       when: admin_username is not defined or admin_username is none
       tags: [ always ]

     - fail: msg="admin_ssh_publickey is not defined or is empty"
       when: admin_ssh_publickey is not defined or admin_ssh_publickey is none
       tags: [ always ]

     - fail: msg="redhat_subscription_username is not defined or is empty"
       when: redhat_subscription_username is not defined or redhat_subscription_username is none
       tags: [ always ]

     - fail: msg="redhat_subscription_password is not defined or is empty"
       when: redhat_subscription_password is not defined or redhat_subscription_password is none
       tags: [ always ]

     - fail: msg="openshift_master_url not defined or is empty"
       when: openshift_master_url is not defined or openshift_master_url is none
       tags: [ always ]

     - fail: msg="openshift_cloudapps_url is not defined or is empty"
       when: openshift_cloudapps_url is not defined or openshift_cloudpps_url is none
       tags: [ always ]
  roles:
     - { role: azure_preview_modules } # TEMPORARY: It solves a bug on azure_rm_networkinterface
     - { role: "{{ cloud_provider }}_ocp_delete_hosts" }
     - { role: "{{ cloud_provider }}_ocp_compute" }

- name: "ALL: Applying Red Hat Subscription"
  hosts: openshift_bastion, openshift_master_group, openshift_infra_group, openshift_node_group
  gather_facts: False
  become: True
  vars_files:
     - openshift.config
  roles:
     - { role: redhat_subscription }

- name: "BASTION: Preparing host where Installation will take place"
  hosts: openshift_bastion
  gather_facts: false
  become: True
  vars_files:
     - openshift.config
  roles: 
     - { role: ocp_bastion_preparation }

- name: "OPENSHIFT: Preparing Hosts"
  hosts: openshift_master_group, openshift_infra_group, openshift_node_group
  gather_facts: False
  become: True
  vars_files:
     - openshift.config
  roles: 
     - { role: ocp_hosts_preparation }

- name: "Final Steps: Removing SSH"
  hosts: openshift_master_group, openshift_infra_group, openshift_node_group
  gather_facts: False
  become: True
  vars_files:
     - openshift.config
  roles:
     - { role: "{{ cloud_provider }}_remove_ssh" }

