---
- name: "Creating all the necessary hosts for OpenShift. Check the file openshift.config"
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
     - openshift.config
  pre_tasks:
     - fail: msg="redhat_subscription_username is not defined or is empty"
       when: redhat_subscription_username is not defined or redhat_subscription_username is none
       tags: [ always ]

     - fail: msg="redhat_subscription_password is not defined or is empty"
       when: redhat_subscription_password is not defined or redhat_subscription_password is none
       tags: [ always ]

     - fail: msg="openshift_master_url not defined or is empty"
       when: openshift_master_url is not defined or openshift_master_url is none
       tags: [ always ]

     - fail: msg="openshift_cloudapps_url is not defined or is empty"
       when: openshift_cloudapps_url is not defined or openshift_cloudpps_url is none
       tags: [ always ]
  roles:
     - { role: azure_preview_modules } # TEMPORARY: It solves a bug on azure_rm_networkinterface
     - { role: "{{ cloud_provider }}_ocp_delete_hosts" }
     - { role: "{{ cloud_provider }}_ocp_compute" }

- name: "ALL: Applying Red Hat Subscription"
#  hosts: openshift_bastion, openshift_master_group, openshift_infra_group, openshift_node_group
  hosts: all
  gather_facts: False
  become: True
  vars_files:
     - openshift.config
  roles:
     - { role: redhat_subscription }

- name: "BASTION: Preparing with all the necessary tools"
  hosts: openshift_bastion
  gather_facts: False
  become: True
  roles: 
     - { role: ocp_bastion_preparation }

- name: "OPENSHIFT: Preparing Hosts"
  hosts: openshift_master_group, openshift_infra_group, openshift_node_group
  gather_facts: False
  become: True
  vars_files:
     - openshift.config
  roles: 
     - { role: ocp_hosts_preparation }

- name: "Final Steps: Removing SSH"
  hosts: openshift_master_group, openshift_infra_group, openshift_node_group
  gather_facts: False
  become: True
  vars_files:
     - openshift.config
  roles:
     - { role: "{{ cloud_provider }}_remove_ssh" }

