network_address_prefix: "192.168.0.0/16"
network_subnet_address_prefix: "192.168.0.0/24"
network_public_ip_allocation: Dynamic
network_ip_configuration: 
   - { name: "{{ name }}", private_ip_allocation_method: "Dynamic", public_ip_allocation_method: "Dynamic", public_ip_address_name: "{{ name }}" }
network_security_group: 
   - { name: enable_ssh, protocol: "Tcp", destination_port_rage: 22, access: "Allow", priority: 101, direction: "Inbound" }

